version: '3.9'

services:
  order-service:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    deploy:
      replicas: 2
    depends_on:
      - orders-db
    restart: unless-stopped

  orders-db:
    image: "postgres:latest"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=orders_db